version: '11'

services:
  db:
    image: postgres
    restart: always
    container_name: pgdb_container
    environment:
      - POSTGRES_DB=rental_kanojo
      - POSTGRES_USER=rental_kanojo
      - POSTGRES_PASSWORD=rent_a_badwi
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container2
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: Admin@123
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes: 
  postgres:
  pgadmin-data: